// Live allocation data exported from the previous hub (Terms 1–3; Term 4 empty).
// Tuple order: [school, team, coachName, term]
export const OLD_ALLOCATIONS: [string, string, string, string][] = [
  // ── Term 1 ──────────────────────────────────────────────
  ["Bellavista", "Football", "Kabelo", "term1"],
  ["Bellavista", "Volleyball", "Thembi", "term1"],
  ["Bellavista", "Netball", "Elizabeth", "term1"],
  ["Bellavista", "Cricket", "Harnu", "term1"],
  ["Bellavista", "Athletics", "Katheerah", "term1"],
  ["Curro Sagewood", "Cricket", "Tshepiso", "term1"],
  ["Curro Sagewood", "Cricket", "Ross", "term1"],
  ["Curro Sagewood", "Cricket", "Edgar", "term1"],
  ["Curro Sagewood", "Softball", "Kerryn", "term1"],
  ["Curro Halfway Gardens", "Cricket", "Samo", "term1"],
  ["Curro Halfway Gardens", "Cricket", "Kabelo", "term1"],
  ["Curro Halfway Gardens", "TBall", "Musa", "term1"],
  ["Curro Halfway Gardens", "Softball", "Musa", "term1"],
  ["Reddford House Northcliff", "Cricket, Tennis, Basketball", "Paballo", "term1"],
  ["Reddford House Northcliff", "Cricket", "Olothando", "term1"],
  ["Reddford House Northcliff", "Basketball", "Katelyn", "term1"],
  ["Reddford House Northcliff", "Tennis", "Thembi", "term1"],
  ["Reddford House Northcliff", "Athletics", "Musawenkosi", "term1"],
  ["Colin Mann", "Football", "Remi", "term1"],
  ["Parkview Senior", "Cricket", "Daniel", "term1"],
  ["Parkview Junior", "Swimming", "Hadley", "term1"],
  ["Parkview Junior", "Netball", "Refilwe", "term1"],
  ["Parkview Junior", "Cricket", "Busani", "term1"],
  ["Parkview Junior", "Cricket", "Kabelo", "term1"],
  ["Curro Rivonia", "Athletics", "Kea", "term1"],
  ["Curro Rivonia", "Athletics", "Justin", "term1"],
  ["Curro Rivonia", "Athletics", "Bongani", "term1"],
  ["Lonehill International", "Ball Skills", "Bongani", "term1"],
  ["Lonehill International", "Ball Skills", "Thembi", "term1"],
  ["Crawford Sandton", "Tennis", "Jean", "term1"],
  ["Crawford Sandton", "Tennis", "Jolie", "term1"],
  ["Kings LP", "Athletics", "Samokelo", "term1"],
  ["Lion Pride Academy", "Athletics, Touch Rugby", "Breeze", "term1"],
  ["Lion Pride Academy", "Athletics, Girls Football", "Takunda", "term1"],
  ["Lion Pride Academy", "Tennis", "Lasley", "term1"],
  ["Lion Pride Academy", "Tennis", "Kea", "term1"],
  ["Lion Pride Academy", "Touch Rugby", "Sanele", "term1"],
  ["Sandton Sinai", "Football", "Curtis", "term1"],
  ["Sandton Sinai", "Football, Cricket", "Jerome", "term1"],
  ["Sandton Sinai", "Football", "Ross", "term1"],
  ["Sandton Sinai", "Table Tennis", "Tapiwa", "term1"],

  // ── Term 2 ──────────────────────────────────────────────
  ["Bellavista", "u9 Soccer", "Harnu", "term2"],
  ["Bellavista", "u10 Soccer", "Thembi", "term2"],
  ["Bellavista", "u13 Soccer", "Kabelo", "term2"],
  ["Bellavista", "Netball", "Elizabeth", "term2"],
  ["Bellavista", "Netball", "Katheerah", "term2"],
  ["Curro Sagewood", "u9 Soccer", "Oregolele", "term2"],
  ["Curro Sagewood", "u10 Soccer", "Olebogeng", "term2"],
  ["Curro Sagewood", "u11 Soccer", "Ross", "term2"],
  ["Curro Sagewood", "u13 Soccer", "Edgar", "term2"],
  ["Curro Sagewood", "u11 - 13 Girls Soccer", "Unathi", "term2"],
  ["Curro Sagewood", "u9 Rugby", "Ken", "term2"],
  ["Curro Halfway Gardens", "Mini Netball", "Deon", "term2"],
  ["Curro Halfway Gardens", "Mini Football", "Kabelo", "term2"],
  ["Curro Halfway Gardens", "u12 Football", "Victor", "term2"],
  ["Curro Halfway Gardens", "u13 Football", "Siseko", "term2"],
  ["Carlswald", "u9 Netball", "Khanya", "term2"],
  ["Curro Rivonia", "Mini Netball", "Mpho", "term2"],
  ["Curro Rivonia", "Mini Football", "Leora", "term2"],
  ["Curro Rivonia", "u10/u11 Netball", "Keatlegile", "term2"],
  ["Curro Rivonia", "u12/u13 Netball", "Beauty", "term2"],
  ["Curro Rivonia", "u10/u11 Football", "Daniel", "term2"],
  ["Curro Rivonia", "u12/u13 Football", "Lebogang", "term2"],
  ["Curro Rivonia", "u15 Football", "Sibusiso", "term2"],
  ["Curro Rivonia", "u19 Football", "Sipho", "term2"],
  ["Curro Rivonia", "u15 Netball", "Ruvimbo", "term2"],
  ["Curro Rivonia", "u19 Netball", "Paballo", "term2"],
  ["Reddford House Northcliff", "ELS Football and Netball", "Justin", "term2"],
  ["Reddford House Northcliff", "JP Netball", "Shakirah", "term2"],
  ["Reddford House Northcliff", "SP Netball", "Kerryn", "term2"],
  ["Reddford House Northcliff", "SP Netball", "Abbey", "term2"],
  ["Reddford House Northcliff", "College Netball", "Berneeta", "term2"],
  ["Reddford House Northcliff", "College Netball", "Musa", "term2"],
  ["Reddford House Northcliff", "JP Soccer", "Ndumiso", "term2"],
  ["Reddford House Northcliff", "SP Soccer", "Justin", "term2"],
  ["Reddford House Northcliff", "SP Soccer", "Nosipho", "term2"],
  ["Reddford House Northcliff", "College Soccer", "Ndumiso", "term2"],
  ["Parkview Senior", "Jnr Girls Soccer", "Samokelo", "term2"],
  ["Parkview Senior", "Snr Girls Soccer", "Nkuli", "term2"],
  ["Parkview Senior", "u10 Boys Soccer", "Nkuli", "term2"],
  ["Parkview Senior", "u12 Boys Soccer", "Samokelo", "term2"],
  ["Parkview Senior", "u10 Netball", "Kerryn", "term2"],
  ["Parkview Senior", "u11 Netball", "Azande", "term2"],
  ["Parkview Junior", "u8 Netball", "Refilwe", "term2"],
  ["Parkview Junior", "u9 Netball", "Thembi", "term2"],
  ["Curro Thatchfield", "Soccer", "Amyoli", "term2"],
  ["Curro Thatchfield", "Soccer", "Lungile", "term2"],
  ["Curro Savanna City", "u15 & u17 Rugby", "Paul", "term2"],
  ["Colin Mann", "u7 Soccer", "Daniel", "term2"],
  ["Colin Mann", "u8 Soccer", "Tshepiso", "term2"],
  ["Colin Mann", "U9 Soccer", "Masego", "term2"],
  ["Colin Mann", "u11 Soccer", "Busani", "term2"],
  ["Colin Mann", "u12 Soccer", "Remi", "term2"],
  ["Lonehill International", "Ball Skills", "Tshepiso", "term2"],
  ["Lonehill International", "Ball Skills", "Thembi", "term2"],
  ["Crawford Sandton", "Mini Soccer and u12 Boys Soccer", "Jean", "term2"],
  ["Crawford Sandton", "Mini Soccer and u9-u11 Girls Soccer", "Jolie", "term2"],
  ["Reddam Waterfall", "u7 Rugby", "Harnu", "term2"],
  ["Reddam Waterfall", "u8 Rugby", "Nqabayethu", "term2"],
  ["Reddam Waterfall", "u9 Rugby", "Siya", "term2"],
  ["Reddam Waterfall", "u10 - u13 Rugby", "Nhlanhla", "term2"],
  ["Lion Pride Academy", "u7 Boys Soccer", "Sipho", "term2"],
  ["Lion Pride Academy", "u9 Boys Soccer", "Mamello", "term2"],
  ["Lion Pride Academy", "u11 Boys Soccer", "Takunda", "term2"],
  ["Lion Pride Academy", "u13 Boys Soccer", "Lasley", "term2"],
  ["Lion Pride Academy", "u15 Boys Soccer", "Lasley", "term2"],
  ["Lion Pride Academy", "u11 Girls Netball", "Deon", "term2"],
  ["Lion Pride Academy", "u13 Girls Netball", "Mamello", "term2"],
  ["Lion Pride Academy", "Gr1-3 Tennis", "Keatlegile", "term2"],
  ["Lion Pride Academy", "Gr4-9 Tennis", "Tapiwa", "term2"],
  ["Lion Pride Academy", "Gr1-3 Touch Rugby", "Breeze", "term2"],
  ["Lion Pride Academy", "Gr4-9 Touch Rugby", "Sanele", "term2"],
  ["Lion Pride Academy", "Gr6-9 Girls Soccer", "Sipho", "term2"],
  ["Sandton Sinai", "Soccer", "Curtis", "term2"],
  ["Sandton Sinai", "Soccer", "Jerome", "term2"],
  ["Sandton Sinai", "Soccer", "Ross", "term2"],
  ["Sandton Sinai", "Table Tennis", "Paul", "term2"],
  ["Sandton Sinai", "Cricket", "Jerome", "term2"],
  ["Rallim", "Prep Football", "Akimi", "term2"],
  ["Rallim", "High School Football", "Dylan", "term2"],
  ["Rallim", "High School Rugby", "Sergio", "term2"],
  ["Rallim", "u9 Hockey", "Akimi", "term2"],
  ["Rallim", "u10 Hockey", "Shalom", "term2"],
  ["Rallim", "High School Hockey Umpire", "Shalom", "term2"],

  // ── Term 3 ──────────────────────────────────────────────
  ["Curro Sagewood", "u7 Hockey", "Musa", "term3"],
  ["Curro Sagewood", "u8 Hockey", "Lungile", "term3"],
  ["Curro Sagewood", "u10 Boys Hockey", "Musa", "term3"],
  ["Curro Sagewood", "u11 Boys Hockey", "Lungile", "term3"],
  ["Curro Sagewood", "Opens Boys Hockey", "Ross", "term3"],
  ["Curro Halfway Gardens", "U7 Boys Hockey", "Edgar", "term3"],
  ["Curro Halfway Gardens", "U8 Boys Hockey", "Edgar", "term3"],
  ["Curro Halfway Gardens", "u9 Boys Hockey", "Edgar", "term3"],
  ["Curro Halfway Gardens", "u10 Girls Hockey", "Paballo", "term3"],
  ["Curro Halfway Gardens", "u11 Boys Hockey", "Thembi", "term3"],
  ["Curro Halfway Gardens", "Opens Boys B Hockey", "Thembi", "term3"],
  ["Curro Rivonia", "Mini Athletics R-1", "Lasley", "term3"],
  ["Curro Rivonia", "Mini Athletics 2-3", "Lasley", "term3"],
  ["Curro Rivonia", "Mini Hockey R-1", "Na'eel", "term3"],
  ["Curro Rivonia", "Mini Hockey 2-3", "Na'eel", "term3"],
  ["Curro Rivonia", "PS Athletics", "Keatlegile", "term3"],
  ["Curro Rivonia", "PS Athletics", "Samokelo", "term3"],
  ["Curro Rivonia", "PS Hockey U10", "Justin", "term3"],
  ["Curro Rivonia", "PS Hockey U11", "Breyton", "term3"],
  ["Curro Rivonia", "PS Hockey U12", "Abbey", "term3"],
  ["Curro Rivonia", "PS Hockey U13", "Tapiwa", "term3"],
  ["Curro Rivonia", "HS u15 Boys Football", "Lebogang", "term3"],
  ["Curro Rivonia", "HS u19 Boys Football", "Sipho", "term3"],
  ["Curro Rivonia", "HS Girls Football", "Kabelo", "term3"],
  ["Curro Rivonia", "HS Hockey", "Mpho", "term3"],
  ["Colin Mann", "u7 Cricket", "Daniel", "term3"],
  ["Colin Mann", "u8 Cricket", "Tshepiso", "term3"],
  ["Colin Mann", "u9 Cricket", "Harnu", "term3"],
  ["Colin Mann", "u10 Cricket", "Remi", "term3"],
  ["Colin Mann", "2nd Team Cricket", "Busani", "term3"],
  ["St Francis", "u15 Football", "Bahle", "term3"],
  ["St Francis", "u17 Football", "Mahlatsi", "term3"],
  ["St Francis", "u19 Football", "Kamohelo", "term3"],
  ["Carlswald", "Hockey", "Khanya", "term3"],
  ["Crawford Sandton", "Hockey", "Jean", "term3"],
  ["Crawford Sandton", "Hockey", "Jolie", "term3"],
  ["Generation Schools", "Jnr Football", "Sanele", "term3"],
  ["Generation Schools", "Snr Football", "Sanele", "term3"],
  ["Generation Schools", "HS Football", "Tshepiso", "term3"],
  ["Generation Schools", "Jnr Netball", "Elizabeth", "term3"],
  ["Generation Schools", "Snr Netball", "Elizabeth", "term3"],
  ["Generation Schools", "HS Netball", "Azande", "term3"],
  ["Lion Pride Academy", "u7 Boys Soccer", "Siseko", "term3"],
  ["Lion Pride Academy", "u9 Boys Soccer", "Mamello", "term3"],
  ["Lion Pride Academy", "u11 Boys Soccer", "Nosipho", "term3"],
  ["Lion Pride Academy", "u11 Girls Netball", "Deon", "term3"],
  ["Lion Pride Academy", "Gr1-3 Tennis", "Deon", "term3"],
  ["Lion Pride Academy", "GR4-9 Tennis", "Kabelo", "term3"],
  ["Lion Pride Academy", "Gr1-3 Touch Rugby", "Welcome", "term3"],
  ["Lion Pride Academy", "GR4-9 Touch Rugby", "Edgar", "term3"],
  ["Lion Pride Academy", "Gr6-9 Girls Soccer", "Siseko", "term3"],
  ["Sandton Sinai", "Soccer", "Mikael", "term3"],
  ["Sandton Sinai", "Soccer", "Jerome", "term3"],
  ["Sandton Sinai", "Soccer", "Ross", "term3"],
  ["Sandton Sinai", "Table Tennis", "Breyton", "term3"],
  ["Sandton Sinai", "Cricket", "Jerome", "term3"],
  ["Sandton Sinai", "Rugby", "Nhlanhla", "term3"],
  ["Rallim", "Hockey & Football", "Akimi", "term3"],
  ["Rallim", "Hockey", "Shalom", "term3"],
  ["Rallim", "Hockey & Football", "Dylan", "term3"],
  ["Rallim", "Oversee all sport", "Sergio", "term3"],
];
