-- ============================================================
-- Migrate real data from the previous hub (allocations, schools,
-- coach rosters, and leaderboard). Safe to re-run: it clears these
-- four reference tables first, then reloads them.
-- Your users, results, planner submissions, gallery, resources and
-- settings are NOT touched.
-- ============================================================

BEGIN;

TRUNCATE allocations, coaches, live_log, schools RESTART IDENTITY CASCADE;

-- Schools
INSERT INTO schools (name) VALUES
  ('Bellavista'),
  ('Carlswald'),
  ('Colin Mann'),
  ('Crawford Sandton'),
  ('Curro Halfway Gardens'),
  ('Curro Rivonia'),
  ('Curro Sagewood'),
  ('Curro Savanna City'),
  ('Curro Thatchfield'),
  ('Generation Schools'),
  ('Kings LP'),
  ('Lion Pride Academy'),
  ('Lonehill International'),
  ('Parkview Junior'),
  ('Parkview Senior'),
  ('Rallim'),
  ('Reddam Waterfall'),
  ('Reddford House Northcliff'),
  ('Sandton Sinai'),
  ('St Francis');

-- Allocations (all terms)
INSERT INTO allocations (school, team, coach_name, term) VALUES
  ('Bellavista', 'Football', 'Kabelo', 'term1'),
  ('Bellavista', 'Volleyball', 'Thembi', 'term1'),
  ('Bellavista', 'Netball', 'Elizabeth', 'term1'),
  ('Bellavista', 'Cricket', 'Harnu', 'term1'),
  ('Bellavista', 'Athletics', 'Katheerah', 'term1'),
  ('Curro Sagewood', 'Cricket', 'Tshepiso', 'term1'),
  ('Curro Sagewood', 'Cricket', 'Ross', 'term1'),
  ('Curro Sagewood', 'Cricket', 'Edgar', 'term1'),
  ('Curro Sagewood', 'Softball', 'Kerryn', 'term1'),
  ('Curro Halfway Gardens', 'Cricket', 'Samo', 'term1'),
  ('Curro Halfway Gardens', 'Cricket', 'Kabelo', 'term1'),
  ('Curro Halfway Gardens', 'TBall', 'Musa', 'term1'),
  ('Curro Halfway Gardens', 'Softball', 'Musa', 'term1'),
  ('Reddford House Northcliff', 'Cricket, Tennis, Basketball', 'Paballo', 'term1'),
  ('Reddford House Northcliff', 'Cricket', 'Olothando', 'term1'),
  ('Reddford House Northcliff', 'Basketball', 'Katelyn', 'term1'),
  ('Reddford House Northcliff', 'Tennis', 'Thembi', 'term1'),
  ('Reddford House Northcliff', 'Athletics', 'Musawenkosi', 'term1'),
  ('Colin Mann', 'Football', 'Remi', 'term1'),
  ('Parkview Senior', 'Cricket', 'Daniel', 'term1'),
  ('Parkview Junior', 'Swimming', 'Hadley', 'term1'),
  ('Parkview Junior', 'Netball', 'Refilwe', 'term1'),
  ('Parkview Junior', 'Cricket', 'Busani', 'term1'),
  ('Parkview Junior', 'Cricket', 'Kabelo', 'term1'),
  ('Curro Rivonia', 'Athletics', 'Kea', 'term1'),
  ('Curro Rivonia', 'Athletics', 'Justin', 'term1'),
  ('Curro Rivonia', 'Athletics', 'Bongani', 'term1'),
  ('Lonehill International', 'Ball Skills', 'Bongani', 'term1'),
  ('Lonehill International', 'Ball Skills', 'Thembi', 'term1'),
  ('Crawford Sandton', 'Tennis', 'Jean', 'term1'),
  ('Crawford Sandton', 'Tennis', 'Jolie', 'term1'),
  ('Kings LP', 'Athletics', 'Samokelo', 'term1'),
  ('Lion Pride Academy', 'Athletics, Touch Rugby', 'Breeze', 'term1'),
  ('Lion Pride Academy', 'Athletics, Girls Football', 'Takunda', 'term1'),
  ('Lion Pride Academy', 'Tennis', 'Lasley', 'term1'),
  ('Lion Pride Academy', 'Tennis', 'Kea', 'term1'),
  ('Lion Pride Academy', 'Touch Rugby', 'Sanele', 'term1'),
  ('Sandton Sinai', 'Football', 'Curtis', 'term1'),
  ('Sandton Sinai', 'Football, Cricket', 'Jerome', 'term1'),
  ('Sandton Sinai', 'Football', 'Ross', 'term1'),
  ('Sandton Sinai', 'Table Tennis', 'Tapiwa', 'term1'),
  ('Bellavista', 'u9 Soccer', 'Harnu', 'term2'),
  ('Bellavista', 'u10 Soccer', 'Thembi', 'term2'),
  ('Bellavista', 'u13 Soccer', 'Kabelo', 'term2'),
  ('Bellavista', 'Netball', 'Elizabeth', 'term2'),
  ('Bellavista', 'Netball', 'Katheerah', 'term2'),
  ('Curro Sagewood', 'u9 Soccer', 'Oregolele', 'term2'),
  ('Curro Sagewood', 'u10 Soccer', 'Olebogeng', 'term2'),
  ('Curro Sagewood', 'u11 Soccer', 'Ross', 'term2'),
  ('Curro Sagewood', 'u13 Soccer', 'Edgar', 'term2'),
  ('Curro Sagewood', 'u11 - 13 Girls Soccer', 'Unathi', 'term2'),
  ('Curro Sagewood', 'u9 Rugby', 'Ken', 'term2'),
  ('Curro Halfway Gardens', 'Mini Netball', 'Deon', 'term2'),
  ('Curro Halfway Gardens', 'Mini Football', 'Kabelo', 'term2'),
  ('Curro Halfway Gardens', 'u12 Football', 'Victor', 'term2'),
  ('Curro Halfway Gardens', 'u13 Football', 'Siseko', 'term2'),
  ('Carlswald', 'u9 Netball', 'Khanya', 'term2'),
  ('Curro Rivonia', 'Mini Netball', 'Mpho', 'term2'),
  ('Curro Rivonia', 'Mini Football', 'Leora', 'term2'),
  ('Curro Rivonia', 'u10/u11 Netball', 'Keatlegile', 'term2'),
  ('Curro Rivonia', 'u12/u13 Netball', 'Beauty', 'term2'),
  ('Curro Rivonia', 'u10/u11 Football', 'Daniel', 'term2'),
  ('Curro Rivonia', 'u12/u13 Football', 'Lebogang', 'term2'),
  ('Curro Rivonia', 'u15 Football', 'Sibusiso', 'term2'),
  ('Curro Rivonia', 'u19 Football', 'Sipho', 'term2'),
  ('Curro Rivonia', 'u15 Netball', 'Ruvimbo', 'term2'),
  ('Curro Rivonia', 'u19 Netball', 'Paballo', 'term2'),
  ('Reddford House Northcliff', 'ELS Football and Netball', 'Justin', 'term2'),
  ('Reddford House Northcliff', 'JP Netball', 'Shakirah', 'term2'),
  ('Reddford House Northcliff', 'SP Netball', 'Kerryn', 'term2'),
  ('Reddford House Northcliff', 'SP Netball', 'Abbey', 'term2'),
  ('Reddford House Northcliff', 'College Netball', 'Berneeta', 'term2'),
  ('Reddford House Northcliff', 'College Netball', 'Musa', 'term2'),
  ('Reddford House Northcliff', 'JP Soccer', 'Ndumiso', 'term2'),
  ('Reddford House Northcliff', 'SP Soccer', 'Justin', 'term2'),
  ('Reddford House Northcliff', 'SP Soccer', 'Nosipho', 'term2'),
  ('Reddford House Northcliff', 'College Soccer', 'Ndumiso', 'term2'),
  ('Parkview Senior', 'Jnr Girls Soccer', 'Samokelo', 'term2'),
  ('Parkview Senior', 'Snr Girls Soccer', 'Nkuli', 'term2'),
  ('Parkview Senior', 'u10 Boys Soccer', 'Nkuli', 'term2'),
  ('Parkview Senior', 'u12 Boys Soccer', 'Samokelo', 'term2'),
  ('Parkview Senior', 'u10 Netball', 'Kerryn', 'term2'),
  ('Parkview Senior', 'u11 Netball', 'Azande', 'term2'),
  ('Parkview Junior', 'u8 Netball', 'Refilwe', 'term2'),
  ('Parkview Junior', 'u9 Netball', 'Thembi', 'term2'),
  ('Curro Thatchfield', 'Soccer', 'Amyoli', 'term2'),
  ('Curro Thatchfield', 'Soccer', 'Lungile', 'term2'),
  ('Curro Savanna City', 'u15 & u17 Rugby', 'Paul', 'term2'),
  ('Colin Mann', 'u7 Soccer', 'Daniel', 'term2'),
  ('Colin Mann', 'u8 Soccer', 'Tshepiso', 'term2'),
  ('Colin Mann', 'U9 Soccer', 'Masego', 'term2'),
  ('Colin Mann', 'u11 Soccer', 'Busani', 'term2'),
  ('Colin Mann', 'u12 Soccer', 'Remi', 'term2'),
  ('Lonehill International', 'Ball Skills', 'Tshepiso', 'term2'),
  ('Lonehill International', 'Ball Skills', 'Thembi', 'term2'),
  ('Crawford Sandton', 'Mini Soccer and u12 Boys Soccer', 'Jean', 'term2'),
  ('Crawford Sandton', 'Mini Soccer and u9-u11 Girls Soccer', 'Jolie', 'term2'),
  ('Reddam Waterfall', 'u7 Rugby', 'Harnu', 'term2'),
  ('Reddam Waterfall', 'u8 Rugby', 'Nqabayethu', 'term2'),
  ('Reddam Waterfall', 'u9 Rugby', 'Siya', 'term2'),
  ('Reddam Waterfall', 'u10 - u13 Rugby', 'Nhlanhla', 'term2'),
  ('Lion Pride Academy', 'u7 Boys Soccer', 'Sipho', 'term2'),
  ('Lion Pride Academy', 'u9 Boys Soccer', 'Mamello', 'term2'),
  ('Lion Pride Academy', 'u11 Boys Soccer', 'Takunda', 'term2'),
  ('Lion Pride Academy', 'u13 Boys Soccer', 'Lasley', 'term2'),
  ('Lion Pride Academy', 'u15 Boys Soccer', 'Lasley', 'term2'),
  ('Lion Pride Academy', 'u11 Girls Netball', 'Deon', 'term2'),
  ('Lion Pride Academy', 'u13 Girls Netball', 'Mamello', 'term2'),
  ('Lion Pride Academy', 'Gr1-3 Tennis', 'Keatlegile', 'term2'),
  ('Lion Pride Academy', 'Gr4-9 Tennis', 'Tapiwa', 'term2'),
  ('Lion Pride Academy', 'Gr1-3 Touch Rugby', 'Breeze', 'term2'),
  ('Lion Pride Academy', 'Gr4-9 Touch Rugby', 'Sanele', 'term2'),
  ('Lion Pride Academy', 'Gr6-9 Girls Soccer', 'Sipho', 'term2'),
  ('Sandton Sinai', 'Soccer', 'Curtis', 'term2'),
  ('Sandton Sinai', 'Soccer', 'Jerome', 'term2'),
  ('Sandton Sinai', 'Soccer', 'Ross', 'term2'),
  ('Sandton Sinai', 'Table Tennis', 'Paul', 'term2'),
  ('Sandton Sinai', 'Cricket', 'Jerome', 'term2'),
  ('Rallim', 'Prep Football', 'Akimi', 'term2'),
  ('Rallim', 'High School Football', 'Dylan', 'term2'),
  ('Rallim', 'High School Rugby', 'Sergio', 'term2'),
  ('Rallim', 'u9 Hockey', 'Akimi', 'term2'),
  ('Rallim', 'u10 Hockey', 'Shalom', 'term2'),
  ('Rallim', 'High School Hockey Umpire', 'Shalom', 'term2'),
  ('Curro Sagewood', 'u7 Hockey', 'Musa', 'term3'),
  ('Curro Sagewood', 'u8 Hockey', 'Lungile', 'term3'),
  ('Curro Sagewood', 'u10 Boys Hockey', 'Musa', 'term3'),
  ('Curro Sagewood', 'u11 Boys Hockey', 'Lungile', 'term3'),
  ('Curro Sagewood', 'Opens Boys Hockey', 'Ross', 'term3'),
  ('Curro Halfway Gardens', 'U7 Boys Hockey', 'Edgar', 'term3'),
  ('Curro Halfway Gardens', 'U8 Boys Hockey', 'Edgar', 'term3'),
  ('Curro Halfway Gardens', 'u9 Boys Hockey', 'Edgar', 'term3'),
  ('Curro Halfway Gardens', 'u10 Girls Hockey', 'Paballo', 'term3'),
  ('Curro Halfway Gardens', 'u11 Boys Hockey', 'Thembi', 'term3'),
  ('Curro Halfway Gardens', 'Opens Boys B Hockey', 'Thembi', 'term3'),
  ('Curro Rivonia', 'Mini Athletics R-1', 'Lasley', 'term3'),
  ('Curro Rivonia', 'Mini Athletics 2-3', 'Lasley', 'term3'),
  ('Curro Rivonia', 'Mini Hockey R-1', 'Na''eel', 'term3'),
  ('Curro Rivonia', 'Mini Hockey 2-3', 'Na''eel', 'term3'),
  ('Curro Rivonia', 'PS Athletics', 'Keatlegile', 'term3'),
  ('Curro Rivonia', 'PS Athletics', 'Samokelo', 'term3'),
  ('Curro Rivonia', 'PS Hockey U10', 'Justin', 'term3'),
  ('Curro Rivonia', 'PS Hockey U11', 'Breyton', 'term3'),
  ('Curro Rivonia', 'PS Hockey U12', 'Abbey', 'term3'),
  ('Curro Rivonia', 'PS Hockey U13', 'Tapiwa', 'term3'),
  ('Curro Rivonia', 'HS u15 Boys Football', 'Lebogang', 'term3'),
  ('Curro Rivonia', 'HS u19 Boys Football', 'Sipho', 'term3'),
  ('Curro Rivonia', 'HS Girls Football', 'Kabelo', 'term3'),
  ('Curro Rivonia', 'HS Hockey', 'Mpho', 'term3'),
  ('Colin Mann', 'u7 Cricket', 'Daniel', 'term3'),
  ('Colin Mann', 'u8 Cricket', 'Tshepiso', 'term3'),
  ('Colin Mann', 'u9 Cricket', 'Harnu', 'term3'),
  ('Colin Mann', 'u10 Cricket', 'Remi', 'term3'),
  ('Colin Mann', '2nd Team Cricket', 'Busani', 'term3'),
  ('St Francis', 'u15 Football', 'Bahle', 'term3'),
  ('St Francis', 'u17 Football', 'Mahlatsi', 'term3'),
  ('St Francis', 'u19 Football', 'Kamohelo', 'term3'),
  ('Carlswald', 'Hockey', 'Khanya', 'term3'),
  ('Crawford Sandton', 'Hockey', 'Jean', 'term3'),
  ('Crawford Sandton', 'Hockey', 'Jolie', 'term3'),
  ('Generation Schools', 'Jnr Football', 'Sanele', 'term3'),
  ('Generation Schools', 'Snr Football', 'Sanele', 'term3'),
  ('Generation Schools', 'HS Football', 'Tshepiso', 'term3'),
  ('Generation Schools', 'Jnr Netball', 'Elizabeth', 'term3'),
  ('Generation Schools', 'Snr Netball', 'Elizabeth', 'term3'),
  ('Generation Schools', 'HS Netball', 'Azande', 'term3'),
  ('Lion Pride Academy', 'u7 Boys Soccer', 'Siseko', 'term3'),
  ('Lion Pride Academy', 'u9 Boys Soccer', 'Mamello', 'term3'),
  ('Lion Pride Academy', 'u11 Boys Soccer', 'Nosipho', 'term3'),
  ('Lion Pride Academy', 'u11 Girls Netball', 'Deon', 'term3'),
  ('Lion Pride Academy', 'Gr1-3 Tennis', 'Deon', 'term3'),
  ('Lion Pride Academy', 'GR4-9 Tennis', 'Kabelo', 'term3'),
  ('Lion Pride Academy', 'Gr1-3 Touch Rugby', 'Welcome', 'term3'),
  ('Lion Pride Academy', 'GR4-9 Touch Rugby', 'Edgar', 'term3'),
  ('Lion Pride Academy', 'Gr6-9 Girls Soccer', 'Siseko', 'term3'),
  ('Sandton Sinai', 'Soccer', 'Mikael', 'term3'),
  ('Sandton Sinai', 'Soccer', 'Jerome', 'term3'),
  ('Sandton Sinai', 'Soccer', 'Ross', 'term3'),
  ('Sandton Sinai', 'Table Tennis', 'Breyton', 'term3'),
  ('Sandton Sinai', 'Cricket', 'Jerome', 'term3'),
  ('Sandton Sinai', 'Rugby', 'Nhlanhla', 'term3'),
  ('Rallim', 'Hockey & Football', 'Akimi', 'term3'),
  ('Rallim', 'Hockey', 'Shalom', 'term3'),
  ('Rallim', 'Hockey & Football', 'Dylan', 'term3'),
  ('Rallim', 'Oversee all sport', 'Sergio', 'term3');

-- Coaches roster (term1)
INSERT INTO coaches (name, term) VALUES
  ('Kabelo', 'term1'),
  ('Thembi', 'term1'),
  ('Elizabeth', 'term1'),
  ('Harnu', 'term1'),
  ('Katheerah', 'term1'),
  ('Tshepiso', 'term1'),
  ('Ross', 'term1'),
  ('Edgar', 'term1'),
  ('Kerryn', 'term1'),
  ('Samo', 'term1'),
  ('Musa', 'term1'),
  ('Paballo', 'term1'),
  ('Olothando', 'term1'),
  ('Katelyn', 'term1'),
  ('Musawenkosi', 'term1'),
  ('Remi', 'term1'),
  ('Daniel', 'term1'),
  ('Hadley', 'term1'),
  ('Refilwe', 'term1'),
  ('Busani', 'term1'),
  ('Kea', 'term1'),
  ('Justin', 'term1'),
  ('Bongani', 'term1'),
  ('Jean', 'term1'),
  ('Jolie', 'term1'),
  ('Samokelo', 'term1'),
  ('Breeze', 'term1'),
  ('Takunda', 'term1'),
  ('Lasley', 'term1'),
  ('Sanele', 'term1'),
  ('Curtis', 'term1'),
  ('Jerome', 'term1'),
  ('Tapiwa', 'term1');

-- Leaderboard (term1)
INSERT INTO live_log (entity_name, points, term) VALUES
  ('Kabelo', 0, 'term1'),
  ('Thembi', 0, 'term1'),
  ('Elizabeth', 0, 'term1'),
  ('Harnu', 0, 'term1'),
  ('Katheerah', 0, 'term1'),
  ('Tshepiso', 0, 'term1'),
  ('Ross', 0, 'term1'),
  ('Edgar', 0, 'term1'),
  ('Kerryn', 0, 'term1'),
  ('Samo', 0, 'term1'),
  ('Musa', 0, 'term1'),
  ('Paballo', 0, 'term1'),
  ('Olothando', 0, 'term1'),
  ('Katelyn', 0, 'term1'),
  ('Musawenkosi', 0, 'term1'),
  ('Remi', 0, 'term1'),
  ('Daniel', 0, 'term1'),
  ('Hadley', 0, 'term1'),
  ('Refilwe', 0, 'term1'),
  ('Busani', 0, 'term1'),
  ('Kea', 0, 'term1'),
  ('Justin', 0, 'term1'),
  ('Bongani', 0, 'term1'),
  ('Jean', 0, 'term1'),
  ('Jolie', 0, 'term1'),
  ('Samokelo', 0, 'term1'),
  ('Breeze', 0, 'term1'),
  ('Takunda', 0, 'term1'),
  ('Lasley', 0, 'term1'),
  ('Sanele', 0, 'term1'),
  ('Curtis', 0, 'term1'),
  ('Jerome', 0, 'term1'),
  ('Tapiwa', 0, 'term1');

-- Coaches roster (term2)
INSERT INTO coaches (name, term) VALUES
  ('Harnu', 'term2'),
  ('Thembi', 'term2'),
  ('Kabelo', 'term2'),
  ('Elizabeth', 'term2'),
  ('Katheerah', 'term2'),
  ('Oregolele', 'term2'),
  ('Olebogeng', 'term2'),
  ('Ross', 'term2'),
  ('Edgar', 'term2'),
  ('Unathi', 'term2'),
  ('Ken', 'term2'),
  ('Deon', 'term2'),
  ('Victor', 'term2'),
  ('Siseko', 'term2'),
  ('Khanya', 'term2'),
  ('Mpho', 'term2'),
  ('Leora', 'term2'),
  ('Keatlegile', 'term2'),
  ('Beauty', 'term2'),
  ('Daniel', 'term2'),
  ('Lebogang', 'term2'),
  ('Sibusiso', 'term2'),
  ('Sipho', 'term2'),
  ('Ruvimbo', 'term2'),
  ('Paballo', 'term2'),
  ('Justin', 'term2'),
  ('Shakirah', 'term2'),
  ('Kerryn', 'term2'),
  ('Abbey', 'term2'),
  ('Berneeta', 'term2'),
  ('Musa', 'term2'),
  ('Ndumiso', 'term2'),
  ('Nosipho', 'term2'),
  ('Samokelo', 'term2'),
  ('Nkuli', 'term2'),
  ('Azande', 'term2'),
  ('Refilwe', 'term2'),
  ('Amyoli', 'term2'),
  ('Lungile', 'term2'),
  ('Paul', 'term2'),
  ('Tshepiso', 'term2'),
  ('Masego', 'term2'),
  ('Busani', 'term2'),
  ('Remi', 'term2'),
  ('Jean', 'term2'),
  ('Jolie', 'term2'),
  ('Nqabayethu', 'term2'),
  ('Siya', 'term2'),
  ('Nhlanhla', 'term2'),
  ('Mamello', 'term2'),
  ('Takunda', 'term2'),
  ('Lasley', 'term2'),
  ('Tapiwa', 'term2'),
  ('Breeze', 'term2'),
  ('Sanele', 'term2'),
  ('Curtis', 'term2'),
  ('Jerome', 'term2'),
  ('Akimi', 'term2'),
  ('Dylan', 'term2'),
  ('Sergio', 'term2'),
  ('Shalom', 'term2');

-- Leaderboard (term2)
INSERT INTO live_log (entity_name, points, term) VALUES
  ('Harnu', 0, 'term2'),
  ('Thembi', 0, 'term2'),
  ('Kabelo', 0, 'term2'),
  ('Elizabeth', 0, 'term2'),
  ('Katheerah', 0, 'term2'),
  ('Oregolele', 0, 'term2'),
  ('Olebogeng', 0, 'term2'),
  ('Ross', 0, 'term2'),
  ('Edgar', 0, 'term2'),
  ('Unathi', 0, 'term2'),
  ('Ken', 0, 'term2'),
  ('Deon', 0, 'term2'),
  ('Victor', 0, 'term2'),
  ('Siseko', 0, 'term2'),
  ('Khanya', 0, 'term2'),
  ('Mpho', 0, 'term2'),
  ('Leora', 0, 'term2'),
  ('Keatlegile', 0, 'term2'),
  ('Beauty', 0, 'term2'),
  ('Daniel', 0, 'term2'),
  ('Lebogang', 0, 'term2'),
  ('Sibusiso', 0, 'term2'),
  ('Sipho', 0, 'term2'),
  ('Ruvimbo', 0, 'term2'),
  ('Paballo', 0, 'term2'),
  ('Justin', 0, 'term2'),
  ('Shakirah', 0, 'term2'),
  ('Kerryn', 0, 'term2'),
  ('Abbey', 0, 'term2'),
  ('Berneeta', 0, 'term2'),
  ('Musa', 0, 'term2'),
  ('Ndumiso', 0, 'term2'),
  ('Nosipho', 0, 'term2'),
  ('Samokelo', 0, 'term2'),
  ('Nkuli', 0, 'term2'),
  ('Azande', 0, 'term2'),
  ('Refilwe', 0, 'term2'),
  ('Amyoli', 0, 'term2'),
  ('Lungile', 0, 'term2'),
  ('Paul', 0, 'term2'),
  ('Tshepiso', 0, 'term2'),
  ('Masego', 0, 'term2'),
  ('Busani', 0, 'term2'),
  ('Remi', 0, 'term2'),
  ('Jean', 0, 'term2'),
  ('Jolie', 0, 'term2'),
  ('Nqabayethu', 0, 'term2'),
  ('Siya', 0, 'term2'),
  ('Nhlanhla', 0, 'term2'),
  ('Mamello', 0, 'term2'),
  ('Takunda', 0, 'term2'),
  ('Lasley', 0, 'term2'),
  ('Tapiwa', 0, 'term2'),
  ('Breeze', 0, 'term2'),
  ('Sanele', 0, 'term2'),
  ('Curtis', 0, 'term2'),
  ('Jerome', 0, 'term2'),
  ('Akimi', 0, 'term2'),
  ('Dylan', 0, 'term2'),
  ('Sergio', 0, 'term2'),
  ('Shalom', 0, 'term2');

-- Coaches roster (term3)
INSERT INTO coaches (name, term) VALUES
  ('Musa', 'term3'),
  ('Lungile', 'term3'),
  ('Ross', 'term3'),
  ('Edgar', 'term3'),
  ('Paballo', 'term3'),
  ('Thembi', 'term3'),
  ('Lasley', 'term3'),
  ('Na''eel', 'term3'),
  ('Keatlegile', 'term3'),
  ('Samokelo', 'term3'),
  ('Justin', 'term3'),
  ('Breyton', 'term3'),
  ('Abbey', 'term3'),
  ('Tapiwa', 'term3'),
  ('Lebogang', 'term3'),
  ('Sipho', 'term3'),
  ('Kabelo', 'term3'),
  ('Mpho', 'term3'),
  ('Daniel', 'term3'),
  ('Tshepiso', 'term3'),
  ('Harnu', 'term3'),
  ('Remi', 'term3'),
  ('Busani', 'term3'),
  ('Bahle', 'term3'),
  ('Mahlatsi', 'term3'),
  ('Kamohelo', 'term3'),
  ('Khanya', 'term3'),
  ('Jean', 'term3'),
  ('Jolie', 'term3'),
  ('Sanele', 'term3'),
  ('Elizabeth', 'term3'),
  ('Azande', 'term3'),
  ('Siseko', 'term3'),
  ('Mamello', 'term3'),
  ('Nosipho', 'term3'),
  ('Deon', 'term3'),
  ('Welcome', 'term3'),
  ('Mikael', 'term3'),
  ('Jerome', 'term3'),
  ('Nhlanhla', 'term3'),
  ('Akimi', 'term3'),
  ('Shalom', 'term3'),
  ('Dylan', 'term3'),
  ('Sergio', 'term3');

-- Leaderboard (term3)
INSERT INTO live_log (entity_name, points, term) VALUES
  ('Musa', 0, 'term3'),
  ('Lungile', 2, 'term3'),
  ('Ross', 2, 'term3'),
  ('Edgar', 0, 'term3'),
  ('Paballo', 0, 'term3'),
  ('Thembi', 2, 'term3'),
  ('Lasley', 0, 'term3'),
  ('Na''eel', 2, 'term3'),
  ('Keatlegile', 2, 'term3'),
  ('Samokelo', 0, 'term3'),
  ('Justin', 0, 'term3'),
  ('Breyton', 0, 'term3'),
  ('Abbey', 0, 'term3'),
  ('Tapiwa', 0, 'term3'),
  ('Lebogang', 2, 'term3'),
  ('Sipho', 2, 'term3'),
  ('Kabelo', 0, 'term3'),
  ('Mpho', 2, 'term3'),
  ('Daniel', 2, 'term3'),
  ('Tshepiso', 0, 'term3'),
  ('Harnu', 0, 'term3'),
  ('Remi', 0, 'term3'),
  ('Busani', 0, 'term3'),
  ('Bahle', 0, 'term3'),
  ('Mahlatsi', 0, 'term3'),
  ('Kamohelo', 0, 'term3'),
  ('Khanya', 0, 'term3'),
  ('Jean', 0, 'term3'),
  ('Jolie', 0, 'term3'),
  ('Sanele', 0, 'term3'),
  ('Elizabeth', 0, 'term3'),
  ('Azande', 0, 'term3'),
  ('Siseko', 0, 'term3'),
  ('Mamello', 0, 'term3'),
  ('Nosipho', 0, 'term3'),
  ('Deon', 0, 'term3'),
  ('Welcome', 0, 'term3'),
  ('Mikael', 0, 'term3'),
  ('Jerome', 0, 'term3'),
  ('Nhlanhla', 0, 'term3'),
  ('Akimi', 2, 'term3'),
  ('Shalom', 2, 'term3'),
  ('Dylan', 0, 'term3'),
  ('Sergio', 0, 'term3');

COMMIT;
